### ISSUE TITLE
timeout in entry_point_waiter

### ISSUE THREAD

**Issue by juanginzo** [onefinestay/nameko#165]
Timeout in entry_point_waiter doesn't trickle down into wait_for_worker_idle. This becomes a problem is entry_point_waiter timeout is higher than the one in wait_for_worker_idle, as only the lowest timeout value will apply. This causes the entry point waiter to timeout  too soon.

https://github.com/onefinestay/nameko/blob/master/nameko/testing/services.py#L100

**Comment by mattbennett** [comment]
The issue here is that ``entrypoint_waiter`` requires the container to be idle before inserting itself as a dependency. It wouldn't be correct to pass the ``timeout`` value into ``wait_for_worker_idle``, because the insert needs to happen before the waiter even starts counting.

This is a limitation of the way ``entrypoint_waiter`` is designed. If there's a long-running worker you can't use it at all. Furthermore if it's configured to wait on an entrypoint that fires but never completes, it will hang forever (doing ``wait_for_worker_idle`` again, before removing itself as a dependency).

I think the correct solve for this is to redesign the ``entrypoint_waiter`` so it's no longer a dependency.
