### ISSUE TITLE
Feature request / discussion: message validation

### ISSUE THREAD

**Issue by kodonnell** [onefinestay/nameko#345]
I may be wrong, but from what I've read there's no standard way of ensuring that the message sent to a service (e.g. RPC) is valid for a particular service. To be fair, the same can be said for "normal" python. However, I think the difference here is:

- microservices can mean using other services which you didn't write - so there's benefit to having a "contract" (give me X and I'll give you back Y, and don't worry your little head about how I do it).
- duck typing doesn't apply as generically, as we have to serialize/deserialize anyway - which means at some level we're doing type checks (and we only support types we can serialize).
- in addiiton, since we're already serializing/deserializing, there's less cost to type checking.
- many REST frameworks separate serialization/validation from application logic in this way. Microservices are rather similar to REST.

That said, I don't think we can ever fully separate validation logic from application logic, as sometimes it just makes sense to do them together. So I'm not sure what's best. So I'd like to get everyone's opinion, before maybe cutting some code.

Some options:

- do nothing. Leave it to the user to implment their own, if any.
- provide a separate function which validates the message first, before executing the main function. Could do this a few ways through e.g. a separate decorator, or tweaking e.g. `handle_message` of RPC (which already validates e.g. that the signature is correct). It could be explicit (i.e. provide a validation) or dynamic (e.g. look for a function in the service called `__<func>_validator`.
- similarly, adopt some of the serialization/validation approaches of REST frameworks.
- use something like e.g. JSON schema. The benefit of this approach is that it means I can actually get the client to retrieve the (relatively small) schema first, validate, and then send the (possibly large) message to the service, so we get faster response times for validation.
- if required, use a serializer like protobuf which (I think) would provide at least the type checking.
- instead of full validation, use the python type hints, as discussed [here](http://stackoverflow.com/questions/19684434/best-way-to-check-function-arguments-in-python)

My preferred option is the last one: it means you can do the "obvious" validations (e.g. `x` and `y` are numeric), and leave more complex stuff to the function to handle. In addition, it's "native" python (PEP 484), the fastest, easiest to implement, and optional for the user (i.e. nothing changes if they don't provide type annotations).

**Comment by mattbennett** [comment]
You’re right, there is no standard way to do this in nameko. There are many different ways to do validation and I think it’s preferable to leave the choice up to the application developer, rather than codifying a specific way into the framework.

That said, it’s useful to talk about all the various options.

At Student.com we use [marshmallow](https://marshmallow.readthedocs.io/en/latest/) to validate rich objects (e.g. data passed to an “update” API). There’s no hard-and-fast rule on when to use a schema — it’s a function of the complexity of the object, how often it changes, and whether we trust/own the caller.

We also also use marshmallow schemas to describe the “service contract” of our external APIs, which all happen to be RESTful. We don’t use the schemas dynamically though, as you describe. They’re more like formal documentation, which our customers can choose to bake into their clients if they want to.

We haven’t implemented our validators as a decorator, but that would be a nice way to keep boilerplate validation separate from the service method. If the schemas were bound to the entrypoint they would be introspectable too, so you could discover the service contract by inspecting the service class. That would allow you to do things like automatically build documentation.

We use RPC inside our service cluster, between the services we own and control. We don’t need anything more strict than the signature check here, but if we did we might opt for something like Thrift instead of RPC.

I've not used type hints yet so can't really comment on how that might work. Can you still benefit from them if the hinted methods are not called directly?

The (mailing list)[https://groups.google.com/forum/#!forum/nameko-dev] is a better place to continue this discussion, so I'm going to close this issue.
